#include "Utils.h"

#include "Event.h"

const char Event::s_KeyToChar[EKeyboardKey_Max] = 
{
	'0',		//	KEY_0,
	'1',		//	KEY_1,
	'2',		//	KEY_2,
	'3',		//	KEY_3,
	'4',		//	KEY_4,
	'5',		//	KEY_5,
	'6',		//	KEY_6,
	'7',		//	KEY_7,
	'8',		//	KEY_8,
	'9',		//	KEY_9,
	'a',		//	KEY_A,
	'b',		//	KEY_B,
	'c',		//	KEY_C,
	'd',		//	KEY_D,
	'e',		//	KEY_E,
	'f',		//	KEY_F,
	'g',		//	KEY_G,
	'h',		//	KEY_H,
	'i',		//	KEY_I,
	'j',		//	KEY_J,
	'k',		//	KEY_K,
	'l',		//	KEY_L,
	'm',		//	KEY_M,
	'n',		//	KEY_N,
	'o',		//	KEY_O,
	'p',		//	KEY_P,
	'q',		//	KEY_Q,
	'r',		//	KEY_R,
	's',		//	KEY_S,
	't',		//	KEY_T,
	'u',		//	KEY_U,
	'v',		//	KEY_V,
	'w',		//	KEY_W,
	'x',		//	KEY_X,
	'y',		//	KEY_Y,
	'z',		//	KEY_Z,
	' ',		//	KEY_SPACE,
	'.',		//	KEY_PERIOD,
	',',		//	KEY_COMMA,
	'!',		//	KEY_EXLAIM,
	'?',		//	KEY_QUESTION,
	':',		//	KEY_COLON,
	';',		//	KEY_SEMICOLON,
	'\'',		//	KEY_QUOTE,
	'"',		//	KEY_QUOTEDBL,
	'#',		//	KEY_HASH,
	'$',		//	KEY_DOLLAR,
	'&',		//	KEY_AMPERSAND,
	'(',		//	KEY_LPAREN,
	')',		//	KEY_RPAREN,
	'*',		//	KEY_ASTERISK,
	'+',		//	KEY_PLUS,
	'-',		//	KEY_MINUS,
	'/',		//	KEY_SLASH,
	'\\',		//	KEY_BACKSLASH,
	'=',		//	KEY_EQUALS,
	'<',		//	KEY_LESS,
	'>',		//	KEY_GREATER,
	'@',		//	KEY_AT,
	'{',		//	KEY_LBRACKET,
	'}',		//	KEY_RBRACKET,
	'^',		//	KEY_CARET,
	'_',		//	KEY_UNDERSCORE,
	'`',		//	KEY_BACKQUOTE,
	'\n',		//	KEY_ENTER,
	'\b',		//	KEY_BACKSPACE,
	'\t',		//	KEY_TAB,
	0,			//	KEY_LMAJ,
	0,			//	KEY_RMAJ,
	0,			//	KEY_LCTRL,
	0,			//	KEY_RCTRL,
	0,			//	KEY_ALT,
	0,			//	KEY_ALTGR,
	0,			//	KEY_UP,
	0,			//	KEY_RIGHT,
	0,			//	KEY_DOWN,
	0,			//	KEY_LEFT,
	0,			//	KEY_INSERT,
	0,			//	KEY_DELETE,
	0,			//	KEY_HOME,
	0,			//	KEY_END,
	0,			//	KEY_PAGEUP,
	0,			//	KEY_PAGEDOWN,
	0,			//	KEY_ESC,
	0,			//	KEY_F1,
	0,			//	KEY_F2,
	0,			//	KEY_F3,
	0,			//	KEY_F4,
	0,			//	KEY_F5,
	0,			//	KEY_F6,
	0,			//	KEY_F7,
	0,			//	KEY_F8,
	0,			//	KEY_F9,
	0,			//	KEY_F10,
	0,			//	KEY_F11,
	0,			//	KEY_F12,
	0,			//	KEY_F13,
	0,			//	KEY_F14,
	0,			//	KEY_F15,
	0,			//	KEY_NUMLOCK,
	0,			//	KEY_CAPSLOCK,
	0,			//	KEY_SCROLLOCK,
	0,			//	MOUSE_LEFT,
	0,			//	MOUSE_MIDDLE,
	0,			//	MOUSE_RIGHT,
	0,			//	MOUSE_WHEELUP,
	0,			//	MOUSE_WHEELDOWN,
};

Event::Event()
{
}

Event::~Event()
{
}

uint16 Event::GetKeyboardChar() const
{
	return Event::s_KeyToChar[GetKeyboardKey()];
}
